import json
import pickle
import os

acc1_json = """[
{
    "domain": ".x.com",
    "expirationDate": 1772130434.299637,
    "hostOnly": false,
    "httpOnly": true,
    "name": "__cf_bm",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "XHo8nikRStUwD_fIEGd.huWurr9uO9xt2lv98RqJ5Uw-1772128635.2180624-1.0.1.1-Xe30GZ0iMPhQ5_gssnklr7RT0IK28THOsbTEsxEABbGMebvPqeRR.pfkltlJUqMq3GJbEN3EYA59MDBlNcvH2AQY6i55MHlxi49Q_weACxBYmzggVDz2cTqCP3lyVyaj",
    "id": 1
},
{
    "domain": ".x.com",
    "expirationDate": 1787681291.72531,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__cuid",
    "path": "/",
    "sameSite": "lax",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "943eb1ba665741069b71ffc1a44b3087",
    "id": 2
},
{
    "domain": ".x.com",
    "expirationDate": 1785847958.297053,
    "hostOnly": false,
    "httpOnly": true,
    "name": "auth_token",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "4b56a5f1edbcc19da407aaa170c17a81fc877245",
    "id": 3
},
{
    "domain": ".x.com",
    "expirationDate": 1785847959.326973,
    "hostOnly": false,
    "httpOnly": false,
    "name": "ct0",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "b6ed0f65a499b29b31d0d02ef7af0ba3be7d84f52fa98e226c48a83ef02434621a9eab51c0ca5b2b932b05dcdd8b7376223f23c83ab33cdce148deccc08a48d692d80c87085fdddf3409f50ba8de74aa",
    "id": 4
},
{
    "domain": ".x.com",
    "expirationDate": 1774759034,
    "hostOnly": false,
    "httpOnly": false,
    "name": "d_prefs",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "MjoxLGNvbnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw",
    "id": 5
},
{
    "domain": ".x.com",
    "expirationDate": 1772720747.412006,
    "hostOnly": false,
    "httpOnly": false,
    "name": "external_referer",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "padhuUp37zjaIykqEpRnNUcV8SWEXZHH|0|8e8t2xd8A2w%3D",
    "id": 6
},
{
    "domain": ".x.com",
    "expirationDate": 1784129669.774243,
    "hostOnly": false,
    "httpOnly": false,
    "name": "guest_id",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "v1%3A176857767030235663",
    "id": 7
},
{
    "domain": ".x.com",
    "expirationDate": 1787681291.330596,
    "hostOnly": false,
    "httpOnly": false,
    "name": "guest_id_ads",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "v1%3A176857767030235663",
    "id": 8
},
{
    "domain": ".x.com",
    "expirationDate": 1787681291.330733,
    "hostOnly": false,
    "httpOnly": false,
    "name": "guest_id_marketing",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "v1%3A176857767030235663",
    "id": 9
},
{
    "domain": ".x.com",
    "expirationDate": 1785847958.296862,
    "hostOnly": false,
    "httpOnly": true,
    "name": "kdt",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "phyTboOR8IUYFpsG3FlKRMTNhu0k8imIpKJ0kQxn",
    "id": 10
},
{
    "domain": ".x.com",
    "expirationDate": 1785847918.781212,
    "hostOnly": false,
    "httpOnly": false,
    "name": "personalization_id",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "\\"v1_cMcMVxj/9/h27ikSftskaw==\\"",
    "id": 11
},
{
    "domain": ".x.com",
    "expirationDate": 1787681291.330809,
    "hostOnly": false,
    "httpOnly": false,
    "name": "twid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "u%3D1919901307067842560",
    "id": 12
},
{
    "domain": "x.com",
    "expirationDate": 1787256346,
    "hostOnly": true,
    "httpOnly": false,
    "name": "g_state",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "{\\"i_l\\":0,\\"i_ll\\":1771704346164,\\"i_b\\":\\"a8Pfv7d0dHcIp4BjC/p9TAzoUeVJd2/fSreuR51O1NM\\",\\"i_e\\":{\\"enable_itp_optimization\\":0}}",
    "id": 13
},
{
    "domain": "x.com",
    "hostOnly": true,
    "httpOnly": false,
    "name": "lang",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "en",
    "id": 14
}
]"""

acc2_json = """[
    {
        "name": "auth_token",
        "value": "db8cc892a6c345d8321d200d551e5aa7d4cf6fe6",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1804337091.299,
        "storeId": null
    },
    {
        "name": "ph_phc_TXdpocbGVeZVm5VJmAsHTMrCofBQu3e0kN8HGMNGTVW_posthog",
        "value": "%7B%22distinct_id%22%3A%220199ce7d-08b9-71d9-a25f-2cfdb81de31a%22%2C%22%24sesid%22%3A%5B1760119942644%2C%220199cf52-ede1-7c48-a629-f5c780c82c18%22%2C1760119942625%5D%7D",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1791655942,
        "storeId": null
    },
    {
        "name": "guest_id",
        "value": "v1%3A175931669125073890",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1793876691.387,
        "storeId": null
    },
    {
        "name": "twid",
        "value": "u%3D1738140409782767616",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1803665393.984,
        "storeId": null
    },
    {
        "name": "_twitter_sess",
        "value": "BAh7BiIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7AA%253D%253D--1164b91ac812d853b877e93ddb612b7471bebc74",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": null,
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "g_state",
        "value": "{\\"i_l\\":0,\\"i_ll\\":1769777089102,\\"i_b\\":\\"ffKkke5HBOmhbbVH0Tf9vDcS++HclEHa62/fJxgQxx0\\",\\"i_e\\":{\\"enable_itp_optimization\\":0}}",
        "domain": "x.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": null,
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1785329089,
        "storeId": null
    },
    {
        "name": "lang",
        "value": "en",
        "domain": "x.com",
        "hostOnly": true,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": null,
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "des_opt_in",
        "value": "Y",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": null,
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1794665963.846,
        "storeId": null
    },
    {
        "name": "__cf_bm",
        "value": "uAY6DxF6dr86TpUj9dUFieQeBv0UObZ757n3z.ugZnw-1772129331.7811203-1.0.1.1-3za.4MYXXk.k0hNBdz8RBK2lKtbjX932AaiH6vSgEtfxg20Gkf75GK_SpvD6Zp33GfwoGapTU6xSqiMmiO7Oo4f_x6ykrrj7FgAPWglzz3fi1o6dqA9nrtPiJ.9YZmtW",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": null,
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1772131132.271,
        "storeId": null
    },
    {
        "name": "__cuid",
        "value": "520677a1158d4bbb8d1d219c003ce46c",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": false,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1806689333,
        "storeId": null
    },
    {
        "name": "ct0",
        "value": "345ebc5757bf2148e10f6a90159ed0239f4909c4855e662b40e89a016a7571dd23eff38c206a1dc4c340d7a46924e58aefff22d338984bb0ce0ca545e03774898d3ebbd32cd7cc4306a41a97bce134b6",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1804337091.819,
        "storeId": null
    },
    {
        "name": "guest_id_ads",
        "value": "v1%3A175931669125073890",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1806689332.182,
        "storeId": null
    },
    {
        "name": "guest_id_marketing",
        "value": "v1%3A175931669125073890",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1806689332.268,
        "storeId": null
    },
    {
        "name": "kdt",
        "value": "38M8lKwqDzoV9z3Fv4dIgOfIj0CURZz73FX0Hb3r",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": null,
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1804337091.296,
        "storeId": null
    },
    {
        "name": "personalization_id",
        "value": "\\"v1_G/TWEUrpJGL9Dgd6hMMg2g==\\"",
        "domain": ".x.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1804337026.468,
        "storeId": null
    }
]"""

def init_cookies():
    # Make sure we don't overwrite if files exist but we can override twitter_cookies.pkl
    with open("twitter_cookies_1.pkl", "wb") as f:
        pickle.dump(json.loads(acc1_json), f)
        
    with open("twitter_cookies_2.pkl", "wb") as f:
        pickle.dump(json.loads(acc2_json), f)
    print("New cookies saved to twitter_cookies_1.pkl and twitter_cookies_2.pkl")

if __name__ == "__main__":
    init_cookies()
